name: '$(Date:yyyyMMdd)$(Rev:.r)-$(BuildID)'
trigger:
  - master
  - release/*

variables:
  - name: GRADLE_USER_HOME
    value: $(Pipeline.Workspace)/.gradle
  - name: BUILD_ID
    value: $(Build.BuildId)
  - name: GRADLE_JVM_OPTIONS
    value: '-Xmx4000m -Dsonar.projectKey=MSS_Android -Dsonar.projectName="CoronaMelder.Android"'
  - name: GRADLE_OPTIONS
    value: '--build-cache'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
          - task: Cache@2
            displayName: Cache
            inputs:
              key: gradle | gradle/wrapper/gradle-wrapper.jar | "$(Agent.OS)"
              path: $(GRADLE_USER_HOME)
              cacheHitVar: gradle
          - task: Gradle@2
            displayName: Enforce formatting
            inputs:
              gradleOptions: $(GRADLE_JVM_OPTIONS)
              options: $(GRADLE_OPTIONS)
              publishJUnitResults: false
              tasks: spotlessCheck
              steps:
          - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
            displayName: 'Prepare analysis on SonarCloud'
            inputs:
              SonarCloud: 'CIBG SonarCloud'
              organization: cibg
              scannerMode: 'Other'
          - task: Gradle@2
            displayName: Build and test
            inputs:
              gradleWrapperFile: gradlew
              options: $(GRADLE_OPTIONS)
              tasks: 'app:assemDevDebug app:assemDevDebugAndroidTest testDevDebug testDebug app:lintDevDebug'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              testRunTitle: Unit tests
              jdkVersionOption: '1.11'
              gradleOptions: $(GRADLE_JVM_OPTIONS)
              sonarQubeRunAnalysis: true
          - task: DownloadSecureFile@1
            displayName: Download Firebase credentials
            name: firebaseCredentials
            inputs:
              secureFile: firebase-credentials.json
          - bash: |
              echo "##vso[task.setvariable variable=GOOGLE_APPLICATION_CREDENTIALS]$(firebaseCredentials.secureFilePath)"
            displayName: Set Firebase credentials
          - task: Gradle@2
            displayName: Run instrumentation tests
            inputs:
              gradleWrapperFile: gradlew
              options: $(GRADLE_OPTIONS)
              tasks: 'app:runFlank'
              publishJUnitResults: true
              testResultsFiles: '**/fladle/results/**/JUnitReport.xml'
              testRunTitle: Instrumentation tests
              jdkVersionOption: '1.11'
              gradleOptions: $(GRADLE_JVM_OPTIONS)
              sonarQubeRunAnalysis: false
          - task: SonarCloudPublish@1
            displayName: 'Publish results on build summary'
            inputs:
              pollingTimeoutSec: '300'
          # Run distribution on the master and release/ branches only          
          - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')) }}:
            - template: distribute.yml